### ISSUE TITLE
purge-cache-status confusion with the status return type; "Complete" or "Completed" ?

### ISSUE THREAD

**Issue by kemicofa** [imagekit-developer/imagekit-nodejs#11]
https://docs.imagekit.io/api-reference/media-api/purge-cache-status

In the Response example, the documentations talks about:
> The status can be either Pending or Completed

And in the "understanding-response" section, it's mentioned:

> Pending - The request has been successfully submitted, and purging is in progress.
Complete - The purge request has been successfully completed. And now you should get a fresh object. Check the Age header in response to confirm this.

Can we clarify if it's `Completed` or `Complete` ?

**Comment by imagekitio** [comment]
It is `Completed`. The documentation has been updated.
