### ISSUE TITLE
Wrong signature on windows

### ISSUE THREAD

**Issue by imagekitio** [imagekit-developer/imagekit-nodejs#12]
The module internally uses `path.join` which on Windows will format with a backslash `\`, while on Linux will use a `/`. This causes a discrepancy in signatures between the two platforms.

**Comment by skierkyles** [comment]
Hi there, I just created a PR for this bug:
https://github.com/imagekit-developer/imagekit-nodejs/pull/13

**Comment by imagekitio** [comment]
The PR needs work as per [this comment](https://github.com/imagekit-developer/imagekit-nodejs/pull/13#discussion_r494747197)
@skierkyles please let me know if you want to continue working on this.
