### ISSUE TITLE
Add test cases

### ISSUE THREAD

**Issue by imagekitio** [imagekit-developer/imagekit-nodejs#14]
Add URL-generation and upload test cases like - https://github.com/imagekit-developer/imagekit-javascript/tree/master/test

**Comment by aortiz24** [comment]
I'll add the test cases, if you assign them to me!

**Comment by imagekitio** [comment]
@aortiz24 Assigned to you.

You can start by writing a few URL generation test cases and submit a PR so that I can quickly review before you write the rest of them.

For the complete list of test cases to cover for URL-generation, please refer to [JS SDK](https://github.com/imagekit-developer/imagekit-javascript/blob/master/test/url-generation.js).

I am here to help if you any questions or doubts.

**Comment by imagekitio** [comment]
@aortiz24 

**Here is an update**:
The test case for URL generation has been added to the master branch. You can pick up the upload test cases. Please use [nock](https://github.com/nock/nock) to mock network requests.

**Comment by imagekitio** [comment]
Fixed in v 3.1.1
