### ISSUE TITLE
Export Code Coverage to CodeCov

### ISSUE THREAD

**Issue by ahnv** [imagekit-developer/imagekit-nodejs#15]
The Code Coverage generated using `nyc` should be published to [CodeCov](https://codecov.io/github/imagekit-developer/imagekit-nodejs)

Refer to https://github.com/codecov/example-node for implementation

**Comment by prijeshb** [comment]
Hey @ahnv I can take this one. 

Please provide further details regarding it.

**Comment by ahnv** [comment]
Hey @prijeshb,

This is pretty straight forward, the SDK has testing done using `mocha`. 
All that is required to do is generate coverage using any code coverage library like `Blanket.js`, `JSCoverage`, `nyc` or `Istanbul` and then publish it to CodeCov using the [`codecov`](https://github.com/codecov/codecov-node) library.

The code coverage generation and publishing should be added to existing [`Node CI`](https://github.com/imagekit-developer/imagekit-nodejs/actions?query=workflow%3A%22Node+CI%22)

**Comment by prijeshb** [comment]
@ahnv Are we adding any custom values  for branches, lines, functions and statements here ?

**Comment by prijeshb** [comment]
> @ahnv Are we adding any custom values for branches, lines, functions and statements here ?

Or with default config

**Comment by ahnv** [comment]
The default config should be enough for now, branches will be automatically configured when it is uploaded to codecov

**Comment by imagekitio** [comment]
Fixed in v 3.1.1
