### ISSUE TITLE
Integrate new media library APIs

### ISSUE THREAD

**Issue by imagekitio** [imagekit-developer/imagekit-nodejs#16]
New APIs have been added to manage files & folders in the ImageKit Media library. 

The SDK should have wrapper functions and test case for the following APIs:

- [Getting image metadata using URL](https://docs.imagekit.io/api-reference/metadata-api/get-image-metadata-for-uploaded-media-files) for an image file. Change the existing function to accept both `fileId` and remote URL. If the value is a URL, internally call the right API endpoint.
- Bulk [add](https://docs.imagekit.io/api-reference/media-api/add-tags-bulk) or [remove](https://docs.imagekit.io/api-reference/media-api/remove-tags-bulk) tags.
- [Copy](https://docs.imagekit.io/api-reference/media-api/copy-file) or [move](https://docs.imagekit.io/api-reference/media-api/move-file) files.
- [Copy](https://docs.imagekit.io/api-reference/media-api/copy-folder) or [move](https://docs.imagekit.io/api-reference/media-api/move-folder) folder.
- [Get bulk job status](https://docs.imagekit.io/api-reference/media-api/copy-move-folder-status) for copy and move folder jobs.
- [Create folder](https://docs.imagekit.io/api-reference/media-api/create-folder) and [Delete folder](https://docs.imagekit.io/api-reference/media-api/delete-folder)

Checklist before submitting PR
- [x] All methods implemented
- [x] Readme.md changes
- [x] Examples added in sample project `sample/index.js`
- [x] Test cases added for all new methods

**Comment by luisgregson** [comment]
I'd like to be assigned this issue if possible?

**Comment by imagekitio** [comment]
Shipped in version 3.1.2
