### ISSUE TITLE
listFiles is ignoring search/filter parameters

### ISSUE THREAD

**Issue by varguizm** [imagekit-developer/imagekit-nodejs#2]
listFiles is ignoring all of the search/filter parameters listed [here](https://docs.imagekit.io/imagekit-docs/list-and-search-files-api).

This small change seems to do the trick:

Request options for listFiles ([/libs/manage/file.js](https://github.com/imagekit-developer/imagekit-nodejs/blob/master/libs/manage/file.js)) are:
`url : "https://api.imagekit.io/v1/files/",`
`method : "GET",`
`json : listOptions`

and should be:
`url : "https://api.imagekit.io/v1/files/",`
`method : "GET",`
`json : true,`
`qs : listOptions`

**Comment by imagekitio** [comment]
Hello, 

The latest version of this package has fixed the issue. Can you please test if it's working for you?
