### ISSUE TITLE
Support for ESM modules

### ISSUE THREAD

**Issue by Lexpeartha** [imagekit-developer/imagekit-nodejs#34]
Are there any plans to add support to using this library with ESM modules?
It would be more than helpful to have it usable with `import/export` syntax, while also supporting CommonJS for compatibility on current projects(mentioned in typescript docs [here](https://www.typescriptlang.org/docs/handbook/esm-node.html)). 
While this might not be high-priority issue, considering how a lot of modern projects use ESM and don't transpile back to cjs with polyfills, I think it would be beneficial for the package to support both sides.

**Comment by Nickersoft** [comment]
I'm not sure this is fully fixed in the latest version... my Node 16 ESM code still chooses the `cjs` build over `esm`. I think an additional `exports` field may be needed in `package.json` as [described in this SO post](https://stackoverflow.com/a/71088004).

**Comment by imagekitio** [comment]
The final build bundle is for CommonJS but can be imported into ESM projects. This works in verision 4.0.1+

In your package.json set
```json
"type": "module",
```

And import it like
```js
import ImageKit from "imagekit";
```
