### ISSUE TITLE
Support for `overwriteFile` option in upload-request.

### ISSUE THREAD

**Issue by cNille** [imagekit-developer/imagekit-nodejs#35]
According to the API documentation (https://docs.imagekit.io/api-reference/upload-file-api/server-side-file-upload)
it should be possible to specify `overwriteFile`.

The `UploadOptions`-interface in this lib doesn't specify that option and throws typescript errors. Would be nice if it would be updated and in sync with the API docs 👌

**Comment by imagekitio** [comment]
Fixed in 3.2.5
