### ISSUE TITLE
Types for upload metadata are incorrect

### ISSUE THREAD

**Issue by choudlet** [imagekit-developer/imagekit-nodejs#41]
Hi!

I believe the types for imagekit.upload are incorrect when use the query parameter   responseFields: 'metadata'. Typescript compiler shows that the metadata field should be a string where the API is actually returning the metadata object. I have a fix currently with a custom type for that response field but this would be great to be fixed at some point. Thank you! :)

**Comment by imagekitio** [comment]
Thanks @choudlet it will be fixed in next release.

**Comment by imagekitio** [comment]
This is fixed in latest version 4.0.1
