### ISSUE TITLE
Note able to use this package with netlify cli

### ISSUE THREAD

**Issue by giovannilaperna** [imagekit-developer/imagekit-nodejs#42]
I'm trying to use this package on on nuxtjs and netlify functions (AWS lambda functions) on a project deployed on netlify.

I'm using the netlify cli.

As soon as I import the package in a file I get the error mentioned [here](https://github.com/netlify/cli/issues/4612).

This is most likely a bug with Netlify cli because I have used this package successfully in other projects.

However, since in this project I'm able to use other packages but not this one, I'm reaching you to ask if you may have an idea of what can cause the issue.

**Comment by imagekitio** [comment]
Netlify issue fixed - https://github.com/netlify/cli/issues/4612
