### ISSUE TITLE
JSON uploads are always 9 bytes

### ISSUE THREAD

**Issue by shinainaru** [imagekit-developer/imagekit-nodejs#43]
[File size limit](https://docs.imagekit.io/api-reference/upload-file-api/server-side-file-upload) 
The maximum upload file size is limited to 25MB.

- I want to upload the file "teokure.json" the file size is **5.9** MB

![Size of file teokure.json - Teokure](https://user-images.githubusercontent.com/90768067/171996633-1933ea58-f7ac-417e-ac5a-3cd606828295.png)

- This my code for upload the JSON file to ImageKit. Code from [This](https://github.com/imagekit-developer/imagekit-nodejs/blob/f30ad6f9bc157b5f88de824c04ad33fe87e58efd/sample/index.js#L171) 

![My code for imagekit sdk - Teokure](https://user-images.githubusercontent.com/90768067/171996647-c2664baf-5d4b-4c8d-a5fe-98733d577f09.png)

This result is always 9 bytes

![Upload SUS - Teokure](https://user-images.githubusercontent.com/90768067/171996663-6c68a857-7ae1-4041-988c-45d93ba27d8d.png)

**Comment by imagekitio** [comment]
The current code you shared is setting `file` to `filePath`, while it should be `file_base64`
