### ISSUE TITLE
How to stop adding default nonce sring at the filename end

### ISSUE THREAD

**Issue by minamme** [imagekit-developer/imagekit-nodejs#44]
Hi 
When I upload an image imagekit automatically adds a little string to the end of file like
![image](https://user-images.githubusercontent.com/34743206/173046685-815b0f06-d741-4a0f-a930-d0e670c1a53f.png)

How to stop this behavior?

**Comment by ahnv** [comment]
Hey @minamme 

ImageKit Upload API accepts a parameter called `useUniqueFileName`, you can set this to false to prevent the nonce from getting appended in file name. 
You can refer to docs regarding the same https://docs.imagekit.io/api-reference/upload-file-api/server-side-file-upload

Specific to nodejs sdk, you can find the parameters [here](https://github.com/imagekit-developer/imagekit-nodejs/blob/f30ad6f9bc157b5f88de824c04ad33fe87e58efd/tests/upload.js#L95-L148) and [here](https://github.com/imagekit-developer/imagekit-nodejs/blob/f30ad6f9bc157b5f88de824c04ad33fe87e58efd/libs/interfaces/UploadOptions.ts)
