### ISSUE TITLE
Getting `TypeError: ImageKit is not a constructor`

### ISSUE THREAD

**Issue by abouolia** [imagekit-developer/imagekit-nodejs#61]
When imported the `imagekit` using `require` everything work well with no issue, but when imported the package using `import ImageKit from "imagekit"` keep getting `TypeError: ImageKit is not a constructor`, btw use the latest version of `imagekit-nodejs`.

**Comment by imagekitio** [comment]
Please share the minimum code to reproduce this problem.

**Comment by abouolia** [comment]
Actually, i don't have even minimum code just wrote the first like `import ImageKit from "imagekit"` and result of `ImageKit` on console.log is `undefined`.

**Comment by imagekitio** [comment]
I will need more information from you to be able to help you. So please provide me with the minimum source code along with instructions to reproduce this issue, even if it is just one line.

**Comment by georgexchelebiev** [comment]
I got the SDK working twith a nodeJS module, but I am getting the same error as @abouolia when trying to import the ES module of the package.

```
import ImageKitEsM from 'imagekit';
const ImageKit = require('imagekit');
console.log(ImageKit, ImageKitEsM);
```

This is the console output:
```[Function: ImageKit] undefined```

Running nodejs v18.12.1

**Comment by imagekitio** [comment]
Please share your package.json file content.
