### ISSUE TITLE
the customMetadata is missing on updateFileDetails

### ISSUE THREAD

**Issue by craigiet** [imagekit-developer/imagekit-nodejs#62]
#### The `customMetadata` has no effect on `updateFileDetails`

While `customMetadata` defined as an optional object on `FileDetailsOptions` interface. it's value is not used in `updateFileDetails` method as a key inside request body.

https://github.com/imagekit-developer/imagekit-nodejs/blob/cd7e96ddc9729022f070c3c237965bebb157b939/libs/manage/file.ts#L205-L210
https://github.com/imagekit-developer/imagekit-nodejs/blob/6ba9e80efa352cc915083b5db9222ab7b19aceca/libs/interfaces/FileDetails.ts#L9-L35

**Comment by imagekitio** [comment]
Fixed in version 4.1.1
