### ISSUE TITLE
Support uploading through streaming

### ISSUE THREAD

**Issue by piotrkulpinski** [imagekit-developer/imagekit-nodejs#69]
Hi,
I'm trying to set up the ImageKit uploading in Remix app but it's currently only supporting uploads via streams:
https://remix.run/docs/en/v1/guides/file-uploads

Is there a way to do that in ImageKit just like in Cloudinary from the example?

Thanks!

**Comment by imagekitio** [comment]
The SDK supports upload by stream
```js
var ImageKit = require("imagekit");

var imagekit = new ImageKit({
    publicKey : "your_public_api_key",
    privateKey : "your_private_api_key",
    urlEndpoint : "https://ik.imagekit.io/your_imagekit_id/"
});

var stream = fs.createReadStream("file.jpg");
var response = await imagekit.upload({
  file: stream,
  fileName: "file.jpg"
})
```

**Comment by piotrkulpinski** [comment]
@imagekitio Good to know, thanks! 
Could you tell me how that would work with files uploaded via form/formData? 

Thanks!

**Comment by piotrkulpinski** [comment]
I was able to fix it with the help of ChatGPT 😂
