### ISSUE TITLE
imagekit DefinitelyTyped need feedback

### ISSUE THREAD

**Issue by kemicofa** [imagekit-developer/imagekit-nodejs#7]
Noticed imagekit didn't have a DefinitelyTyped and since I need it I've gone ahead and started putting one together.

Feel free to give me some feedback. Probably have some silly mistakes here and there.

Things still todo:
1. Check interface properties for typos and if any are missing
2. Combine common response types
3. Verify all required and optional properties 
4. Test

https://github.com/kemicofa/DefinitelyTyped/blob/imagekit/types/imagekit/index.d.ts

**Comment by imagekitio** [comment]
Thanks, @kemicofa I will have a look at these soon.

**Comment by dodicandra** [comment]
silakan gabungkan atau tarik permintaan, dan silakan gabungkan permintaan tarik ini karena saya memerlukan pengembangan naskah ini

**Comment by kemicofa** [comment]
@dodicandra feel free to help me double check the types with what ImageKit has in their documentation. Also left a few TODOs in the file that need answering before I'll attempt to merge this.

**Comment by romdim** [comment]
Hi @kemicofa, nice work!
I tried your type for getting the Authentication Parameters and saw that the parameters token and timestamp are actually optional, as mentioned here as well: https://github.com/imagekit-developer/imagekit-nodejs#authentication-parameter-generation

So I would suggest the following change:

```
    public getAuthenticationParameters(
      token?: string,
      expire?: number
    ): { token: string; expire: number; signature: string };
```

**Comment by kemicofa** [comment]
@romdim thanks for the help, I've updated it. Don't hesitate to create a PR next time.

**Comment by kemicofa** [comment]
I took some time to add comments for just about everything, allowing us to have quality documentation information when we're coding with the library:

![Capture d’écran 2020-08-25 à 14 40 49](https://user-images.githubusercontent.com/45143945/91175435-17d3ad80-e6e1-11ea-85ea-537b5af6b02d.png)

Just about done with the PR, missing a couple things:

1. Type information and a documentation link to Chained Transformations (for `Transformation` type)
2. Type information for `FileMetadataResponse`

I won't have much time to test it with real code this week.

**Comment by romdim** [comment]
@kemicofa I added info about the Transformation type + a couple of fixes.
I couldn't find more info on FileMetadataResponse other than 2 links.

Imho, the pr is ready to go.

**Comment by kemicofa** [comment]
@romdim good job and thanks for the help! I agree I think it's ready to go.

@imagekitio could you validate the PR? Thanks.

**Comment by kemicofa** [comment]
@romdim @imagekitio it was merged! Closing this.
