### ISSUE TITLE
Feature Request: File Management functions via filePath

### ISSUE THREAD

**Issue by CamTheGoblin** [imagekit-developer/imagekit-nodejs#74]
### Feature Request:
File Management functions via filePath

### The Problem:
It seems like much of the File Management functions use the fileID to lookup the files, But most of the end usage of the files depends on the filePath. I am currently just saving the filePath as most of the time that is all I need after an image has been uploaded, but if I want to run any of the File Management functions on the file like deleting it, I need the fileID instead.  

It seems messy to have to save a reference to both the fileID and filePath, Both will always be unique identifiers for the target file so its just unnecessarily redundant data.

The other option is to only save fileID, but then I have to look up the filePath via .getFileDetails() anytime I want to use the file in the application which is also messy, especially since filePath is what I want the 90% the time.

### Solution:
Here is my suggested solution:

A secondary set of functions for utilizing the filePath as the unique identifier ( i.e. deleteFile**ByPath**() ) . this will leave the current functions as is while giving the additional functionality to those who need it.

For a quick solution that would take care of most of the problem with minimal work, just make update the getFileDetails to work with a filePath (or make a getFileDetails**ByPath**() ). that way the filePath can be what is saved as it is what is needed 90% of the time, and getFileDetails can be called using it to get the fileId when needed.

**Comment by imagekitio** [comment]
We have noted this feedback as part of improvements that we will make in `v2` version. However since this has nothing to do with the SDKs and is dependent on the backend API, I am closing this issue now.
