### ISSUE TITLE
Deprecation of overlays in favor of layers API

### ISSUE THREAD

**Issue by abdelrahman-elkady** [imagekit-developer/imagekit-nodejs#77]
According to [the docs](https://docs.imagekit.io/features/image-transformations/overlay), overlay transformation will be deprecated on 31st Oct 2023 in favor of the [layers API](https://docs.imagekit.io/features/image-transformations/overlay-using-layers#examples)

The current implementation doesn't support the layers API yet as far as I see, I think this needs to be supported and updated in the docs too

**Comment by imagekitio** [comment]
Please use `raw` to specify the layer transformation - https://github.com/imagekit-developer/imagekit-nodejs#list-of-supported-transformations
