### ISSUE TITLE
Can't retrieve folder metadata.

### ISSUE THREAD

**Issue by idavidgeo** [imagekit-developer/imagekit-nodejs#84]
I've assigned a custom metadata item to a folder (folder2 in this case). But I can't figure out a way to retrieve it.

`imagekit.getFileMetadata('folder/folder2')` doesn't work.

**Comment by imagekitio** [comment]
You actually need to fetch the media asset details.
Use this method instead `imagekit.getFileDetails`

**Comment by idavidgeo** [comment]
> You actually need to fetch the media asset details. Use this method instead `imagekit.getFileDetails`
> 
> ```js
> // Using Callback Function
> 
> imagekit.getFileDetails("file_id", function(error, result) {
>     if(error) console.log(error);
>     else console.log(result);
> });
> 
> 
> // Using Promises 
> 
> imagekit.getFileDetails("file_id")
> }).then(response => {
>     console.log(response);
> }).catch(error => {
>     console.log(error);
> });
> ```

Right, but I want the folder metadata, not the file. I've set metadata variables for the folder via the web dashboard and want to retrieve them via API.

**Comment by AmirAjmi** [comment]
I'm running into the same issue and I haven't found any fix at all ? has there been progress since ? can I access the metadata that I set for a folder in the dashboard UI through API ?
thank you

**Comment by manu4543** [comment]
Sorry the V1 API (used by this SDK) doesnt send customMetadata in response. The UI uses a non public v2 api which is not stable and released yet.

re-opened https://github.com/imagekit-developer/imagekit-nodejs/issues/115

**Comment by imagekitio** [comment]
Its fixed.
