### ISSUE TITLE
Support Node.js v21

### ISSUE THREAD

**Issue by adaboese** [imagekit-developer/imagekit-nodejs#85]
At the moment, I am getting warning:

>  WARN  Unsupported engine: wanted: {"node":"^20"} (current: {"node":"v21.4.0","pnpm":"8.12.1"})

**Comment by ankur-dwivedi** [comment]
Hello @adaboese, I've tested with the versions node v21.4.0 and pnpm 8.12.1, and it seems to be working fine for me. I don't think the issue is related to `imagekit`.
