### ISSUE TITLE
Your request contains invalid value for folder parameter.

### ISSUE THREAD

**Issue by thtRajasthaniGuy** [imagekit-developer/imagekit-nodejs#96]
my folder name is only contain alphabet. like govind , but its throw this error

 const res = await imagekit.upload({
      file: fileData,
      fileName: imageName,
      folder: "govind",
      tags: ["clinic", "logo"],
    });

**Comment by ankur-dwivedi** [comment]
Hi @thtRajasthaniGuy, could you please share some additional information to help replicate the issue?

- Your ImageKit ID
- The cURL request you used

**Comment by imagekitio** [comment]
Please open this issue again by sharing reproducible code.
