### ISSUE TITLE
Not able to delete image from imagekit

### ISSUE THREAD

**Issue by bantawa04** [imagekit-developer/imagekit-nodejs#99]
I'm currently using imagekit as primary storage for storing images for my application. I can upload images and access images.

```
export const create = async (image: any) => {
  try {
    const arrayBuffer = await image.arrayBuffer()

    const buffer = Buffer.from(arrayBuffer)

    const response = await imageKit.upload({
      file: buffer, fileName: image.name
    })

    return await prisma.media.create({
      data: {
        fileName: response.name, url: response.url, thumbUrl: response.thumbnailUrl, fileId: response.fileId
      }
    })
  } catch (error) {
    throw error
  }
}

```

but i'm unable to delete the image that was uploaded 

```
export const destroy = async (id: number) => {
  try {
    const media = await prisma.media.findFirst({
      where: { id: id }
    })

    if (media) {
      await imageKit.deleteFile(media.fileId)

      await prisma.media.delete({
        where: { id: media.id }
      })
    }
  } catch (error) {
    throw error
  }
}
```

I get the following response while deleting and getting file by fileId:

```
{
  message: 'The requested file does not exist.',
  help: 'For support kindly contact us at support@imagekit.io .'
}
```

It used to work few weeks back. I have also tried using http request unsing   Authorization: header. But output is same.
The images that i want to delete or access image are present in imagekit.

**Comment by imagekitio** [comment]
Please check if the file exists by calling Get file details API. You can use browser based API try out in docs - https://imagekit.io/docs/api-reference/digital-asset-management-dam/managing-assets/get-file-details

**Comment by imagekitio** [comment]
Closing this issue for now, please provide more details along with fileId and imagekit id for further assistance.
